### ISSUE TITLE
doesn't seem to work with current version of ManagerServer.exe

### ISSUE THREAD

**Issue by bkc** [mprokopov/docker-manager.io#1]
just now I did this

```
docker pull mprokopov/manager.io
docker run --rm mprokopov/manager.io

Manager Server [Version 16.12.31]
Copyright (c) 2016 NGSoftware.  All rights reserved.

Syntax:

    mono ManagerServer.exe [options]

Options:

    -port [number]     Set port on which HTTP server should listen on.
    -path [directory]  Set directory where Manager should look for data.

Examples:

    mono ManagerServer.exe
    mono ManagerServer.exe -port 80
    mono ManagerServer.exe -port 80 -path "/root/.local/share/Manager"


[02:30:54] The type initializer for 'SQLite.SQLiteConnection' threw an exception. (TypeInitializationException)

```

This doesn't seem to be related to not specifying a volume.

I tried rebuilding the Dockerfile using 'FROM mono:latest' but that didn't work..

**Comment by mprokopov** [comment]
That's due to issue with new sqlite library and 86/64-bit versions.
It's discussed here https://forum.manager.io/t/manager-does-not-start-after-recent-update-on-ubuntu/7950/19

Let me check it once more.

**Comment by mprokopov** [comment]
Issue was due to wrong libe_sqlite3 library, so I've compiled manually libe_sqlite3.so and included in image.

wget -O https://raw.githubusercontent.com/ericsink/SQLitePCL.raw/master/sqlite3/sqlite3.c

gcc -shared -fPIC -O -DNDEBUG -DSQLITE_DEFAULT_FOREIGN_KEYS=1 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_RTREE -o libe_sqlite3.so sqlite3.c

**Comment by bkc** [comment]
thanks a lot of looking into this so quickly, it works now..

**Comment by lubos** [comment]
I'm going to temporarily remove 32-bit support from Linux version. Manager will be distributed with 64-bit Sqlite for the time being on Linux.

[I've created an issue in related project](https://github.com/ericsink/SQLitePCL.raw/issues/113) to see if Sqlite binary can be distributed side-by-side for both 32-bit and 64-bit Linux.
